### ISSUE TITLE
Can I use npm instead of yarn?

### ISSUE THREAD

**Issue by shinglyu** [yewstack/yew-wasm-pack-template#13]
I'm curious if this project works with npm as well? The `package.json` looks compatible and I tried to run with `npm install && npm run start:dev`, it seems to work fine. Is there any particular feature that only works on yarn?

I'm not asking you to change yarn to npm. I'm asking because I'm building a tutorial on Rust and WebAssembly. I've already introduced npm earlier sections (while introducing wasm-pack-template), and I'm trying to see if I can ask the student to use npm on this project as well. The tutorial is targeting complete beginners so I want to avoid introducing both npm and yarn and confuse the students.

**Comment by jstarry** [comment]
@shinglyu yes, `npm` is actually probably better than using `yarn` but both work!
