### ISSUE TITLE
Add styling to showcase how to use a sass loader

### ISSUE THREAD

**Issue by jstarry** [yewstack/yew-wasm-pack-template#2]

**Comment by sectore** [comment]
@jstarry ~Does not `Webpack`'s documentation help for you https://webpack.js.org/loaders/sass-loader/ ?~ 

Ah sorry, it seems to be an opened issue by a `YewStack` member than a question :laughing: Just ignore my question ^ ...

**Comment by jstarry** [comment]
No worries! Yeah this is a pretty easy fix, just requires someone to do it 😉
