### ISSUE TITLE
Where is it served to?

### ISSUE THREAD

**Issue by strasdat** [yewstack/yew-wasm-pack-template#25]
If  I understand this example correctly, ``yarn run start:dev`` should serve this site locally. But what is the address?
http://localhost:8080/ does not work.

What am I missing?

**Comment by jstarry** [comment]
Should be http://localhost:8000/

**Comment by strasdat** [comment]
Thanks, I overlooked this line:

```
ℹ ｢wds｣: Project is running at http://localhost:8000/
```
