### ISSUE TITLE
Should `console_error_panic_hook` be moved to `[dev-dependencies]`?

### ISSUE THREAD

**Issue by kellytk** [yewstack/yew-wasm-pack-template#3]
Considering the language and stated performance overhead beginning at https://github.com/yewstack/yew-wasm-pack-template/blob/master/Cargo.toml#L24 should `console_error_panic_hook` be moved to `[dev-dependencies]`?

**Comment by hgzimmerman** [comment]
I think its fine as a default-on feature-gated dependency. Something someone can turn off when they decide to build for deployment.

I think the general practice for yew ecosystem crates is to have everything within reason be enabled by default, but able to be turned off when people decide they need to start caring about wasm file size.
