### ISSUE TITLE
Error: Rust compilation.

### ISSUE THREAD

**Issue by pythoneer** [yewstack/yew-wasm-pack-template#6]
I cloned the repo installed all the things i think are necessary and get the following errors with

```
yarn run build
```

```
yarn run v1.19.2
$ webpack --mode production
🧐  Checking for wasm-pack...

ℹ️  Installing wasm-pack 

Error: Rust compilation.
    at ChildProcess.<anonymous> (/home/naikon/Documents/dev/test/rust/yew/project_test/yew-wasm-pack-template/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:190:16)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

and

```
yarn run start:dev
```

```
yarn run v1.19.2
$ webpack-dev-server --mode development
🧐  Checking for wasm-pack...

ℹ️  Installing wasm-pack 

ℹ ｢wds｣: Project is running at http://localhost:8000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/naikon/Documents/dev/test/rust/yew/project_test/yew-wasm-pack-template/dist
✖ ｢wdm｣: Error: Rust compilation.
    at ChildProcess.<anonymous> (/home/naikon/Documents/dev/test/rust/yew/project_test/yew-wasm-pack-template/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:190:16)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
```

System is ArchLinux and all packages up to date
```
uname -a
Linux archdesk 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
```

Rust version is 1.39 stable

**Comment by dimeola** [comment]
Version: webpack 4.38.0
Time: 41032ms
Built at: 2019-12-25 4:29:42
       Asset       Size  Chunks             Chunk Names
0.todomvc.js  312 bytes       0  [emitted]  
  index.html  405 bytes          [emitted]  
  todomvc.js    364 KiB    main  [emitted]  main
Entrypoint main = todomvc.js
[0] multi (webpack)-dev-server/client?http://localhost:8000 ./bootstrap.js 40 bytes {main} [built]
[./bootstrap.js] 57 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/ansi-regex/index.js] 135 bytes {main} [built]
[./node_modules/html-entities/index.js] 231 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8000] (webpack)-dev-server/client?http://localhost:8000 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./pkg/index.js] 0 bytes {0} [built]
    + 19 hidden modules
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
✖ ｢wdm｣: Hash: 9a6785f945bbe259bac1
Version: webpack 4.38.0
Time: 21ms
Built at: 2019-12-25 4:29:42
 2 assets
Entrypoint main = todomvc.js
   34 modules

ERROR in Rust compilation.
ℹ ｢wdm｣: Failed to compile.

**Comment by losnappas** [comment]
I had the same, then I

1. Did this https://github.com/yewstack/yew-wasm-pack-minimal#1-install-rust-and-wasm-pack
2. Ran `npm run dev` and it downloaded a bunch of stuff.

After that, `start:dev` worked. I'd start by trying out step 2.

**Comment by darrenmeehan** [comment]
My pull request #14 resolves this. `npm install` is required before running the application.

**Comment by darrenmeehan** [comment]
@pythoneer Could you try this again? #14 has now been merged.
